services:
  db:
    image: mysql:8.0
    container_name: folium_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./server/src/database/Folium.sql:/docker-entrypoint-initdb.d/Folium.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
  backend:
    build:
      context: ./server
    container_name: folium_backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
    container_name: folium_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mysql_data: